[target.thumbv7m-unknown-linux-uclibc.dependencies.std]
stage = 0

[target.thumbv7m-unknown-linux-uclibc.dependencies.compiler_builtins]

[patch.crates-io]
compiler_builtins = { path = "/vagrant/repos/compiler-builtins" }
libc = { path = "/vagrant/repos/libc" }